/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as CreateWhiteBoardImport } from './routes/createWhiteBoard'
import { Route as ClassifierImport } from './routes/classifier'
import { Route as IndexImport } from './routes/index'
import { Route as WhiteBoardIdImport } from './routes/whiteBoard/$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const CreateWhiteBoardRoute = CreateWhiteBoardImport.update({
  path: '/createWhiteBoard',
  getParentRoute: () => rootRoute,
} as any)

const ClassifierRoute = ClassifierImport.update({
  path: '/classifier',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WhiteBoardIdRoute = WhiteBoardIdImport.update({
  path: '/whiteBoard/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/classifier': {
      preLoaderRoute: typeof ClassifierImport
      parentRoute: typeof rootRoute
    }
    '/createWhiteBoard': {
      preLoaderRoute: typeof CreateWhiteBoardImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/whiteBoard/$id': {
      preLoaderRoute: typeof WhiteBoardIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ClassifierRoute,
  CreateWhiteBoardRoute,
  SigninRoute,
  SignupRoute,
  WhiteBoardIdRoute,
])

/* prettier-ignore-end */
