/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateWhiteBoardImport } from './routes/createWhiteBoard'
import { Route as ClassifierImport } from './routes/classifier'
import { Route as WhiteBoardIdImport } from './routes/whiteBoard/$id'

// Create/Update Routes

const CreateWhiteBoardRoute = CreateWhiteBoardImport.update({
  path: '/createWhiteBoard',
  getParentRoute: () => rootRoute,
} as any)

const ClassifierRoute = ClassifierImport.update({
  path: '/classifier',
  getParentRoute: () => rootRoute,
} as any)

const WhiteBoardIdRoute = WhiteBoardIdImport.update({
  path: '/whiteBoard/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/classifier': {
      preLoaderRoute: typeof ClassifierImport
      parentRoute: typeof rootRoute
    }
    '/createWhiteBoard': {
      preLoaderRoute: typeof CreateWhiteBoardImport
      parentRoute: typeof rootRoute
    }
    '/whiteBoard/$id': {
      preLoaderRoute: typeof WhiteBoardIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ClassifierRoute,
  CreateWhiteBoardRoute,
  WhiteBoardIdRoute,
])

/* prettier-ignore-end */
