/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WhiteboardImport } from './routes/whiteboard'
import { Route as SocketImport } from './routes/socket'
import { Route as ClassifierImport } from './routes/classifier'

// Create/Update Routes

const WhiteboardRoute = WhiteboardImport.update({
  path: '/whiteboard',
  getParentRoute: () => rootRoute,
} as any)

const SocketRoute = SocketImport.update({
  path: '/socket',
  getParentRoute: () => rootRoute,
} as any)

const ClassifierRoute = ClassifierImport.update({
  path: '/classifier',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/classifier': {
      preLoaderRoute: typeof ClassifierImport
      parentRoute: typeof rootRoute
    }
    '/socket': {
      preLoaderRoute: typeof SocketImport
      parentRoute: typeof rootRoute
    }
    '/whiteboard': {
      preLoaderRoute: typeof WhiteboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ClassifierRoute,
  SocketRoute,
  WhiteboardRoute,
])

/* prettier-ignore-end */
